### ISSUE TITLE
SyntaxHighlighter for <pre>

### ISSUE THREAD

**Issue by demetraa** [KPJS/blog#138]
![image](https://cloud.githubusercontent.com/assets/16520197/19193011/9f44d4e8-8ca8-11e6-8fbe-85d50947717a.png)

**Comment by drvic10k** [comment]
shouldn't this be closed now?

**Comment by drvic10k** [comment]
#142 fixed

**Comment by drvic10k** [comment]
more specifically c507e4f1b325f060b60195e317b0d1e1aa3881fc
