### ISSUE TITLE
Server initialization should use logger

### ISSUE THREAD

**Issue by vaclav-antosik** [KPJS/blog#18]
https://github.com/KPJS/blog/blob/master/app.js#L60-L66

**Comment by yohny** [comment]
should it? don't we want it in console? we already log server initialization status using logger [here](https://github.com/KPJS/blog/blob/master/server.js#L46-L51)

**Comment by vaclav-antosik** [comment]
I would prefer to keep output to console but I would extend existing logging (add address, port information)
