### ISSUE TITLE
transform old posts from html file into mongo documents

### ISSUE THREAD

**Issue by yohny** [KPJS/blog#39]
to be able to read our old posts from mongo we need to firs import them into mongo database

**Comment by vaclav-antosik** [comment]
Html files transformed to the json format (content replacements 
" -> \", 
\r\n -> [space], 
\t -> [space], 
\ -> \\) and imported to the database

**Comment by yohny** [comment]
some posts were not converted correctly:
![untitled](https://cloud.githubusercontent.com/assets/5924185/10841736/4142431e-7eec-11e5-8805-f9a171f45915.png)

**Comment by vaclav-antosik** [comment]
FTP and SSH deployment posts reimported.
ANSI document format changed to UTF8

**Comment by yohny** [comment]
I also noticed that some `users` assigned as posts authors are wrong - 2 posts are assigned to @vaclav-antosik and all others to me, which is not correct

**Comment by yohny** [comment]
btw., according to [documentation](https://docs.mongodb.org/manual/reference/database-references/) we should not use DBRef if we are not referencing different collections in `author` field (we are not, for us it's always `users` collection), so in our case manual referencing is recommended

**Comment by vaclav-antosik** [comment]
1, DBRefs field author removed from all documents in posts collection
2, New manual reference filed users_id has been added to all documents in posts collection

Remove command:
db.posts.update({},{$unset: {author:1}},{multi:1})

Add new field:
db.posts.update({_id:ObjectId("5635c7a3610919065e30ee23")},{$set:{users_id:ObjectId("5630e908bbf8af5dd4a9656e")}})

Check command:
db.posts.find({},{_id:1,uri:1,users_id:1}).sort({publishDate:1}).map(function(p) {return {uri:p.uri,author:db.users.findOne({_id:p.users_id}, {_id:0,name:1})}})
