### ISSUE TITLE
add publishDate property to mongo posts

### ISSUE THREAD

**Issue by yohny** [KPJS/blog#40]
to be able to sort posts as the come in time to existence, we need `publishDate` property

**Comment by vaclav-antosik** [comment]
Adds publishDate field to all "post" documents.
Date value used according to github history records.

Update command:
db.posts.update({_id:ObjectId("563259e3e9f8eb1f186793fe")}, {$set:{publishDate:new Date("2015-09-30")}})

Check command:
db.posts.find({}, {title:1, _id:0, publishDate:1}).sort({publishDate:1})
