### ISSUE TITLE
create first blog post

### ISSUE THREAD

**Issue by yohny** [KPJS/blog#8]
screeenshots from first session:
![screenshot from 2015-08-10 16 25 46](https://cloud.githubusercontent.com/assets/5924185/9176544/5176e702-3f8c-11e5-9dd1-87801c76162a.png)
![screenshot from 2015-08-10 16 26 50](https://cloud.githubusercontent.com/assets/5924185/9176545/51789408-3f8c-11e5-8e35-2b61f2c31692.png)
![screenshot from 2015-08-10 16 27 42](https://cloud.githubusercontent.com/assets/5924185/9176547/517a4212-3f8c-11e5-9c5e-fae78acb4415.png)
![screenshot from 2015-08-10 16 30 09](https://cloud.githubusercontent.com/assets/5924185/9176548/517a4a6e-3f8c-11e5-82f2-d3faf98c5d1f.png)
![screenshot from 2015-08-10 16 34 14](https://cloud.githubusercontent.com/assets/5924185/9176549/517c3608-3f8c-11e5-9b97-f0982303b922.png)
![screenshot from 2015-08-10 16 36 44](https://cloud.githubusercontent.com/assets/5924185/9176546/517a4000-3f8c-11e5-9af2-bbdbc04ff830.png)
![screenshot from 2015-08-10 16 43 03](https://cloud.githubusercontent.com/assets/5924185/9176550/518f7d12-3f8c-11e5-9ddf-4a558817a88c.png)
![screenshot from 2015-08-10 16 44 13](https://cloud.githubusercontent.com/assets/5924185/9176551/5191511e-3f8c-11e5-99f8-767674efbcc7.png)
![screenshot from 2015-08-10 17 06 00](https://cloud.githubusercontent.com/assets/5924185/9176553/519445e0-3f8c-11e5-8294-a00e1cb5e636.png)
![screenshot from 2015-08-10 17 48 55](https://cloud.githubusercontent.com/assets/5924185/9176554/519475e2-3f8c-11e5-901f-980989f38175.png)
![screenshot from 2015-08-10 17 49 42](https://cloud.githubusercontent.com/assets/5924185/9176552/51940468-3f8c-11e5-8d09-8a4ba16470f9.png)
![screenshot from 2015-08-10 17 49 51](https://cloud.githubusercontent.com/assets/5924185/9176555/51957cee-3f8c-11e5-8a0f-251aa87b4419.png)
![screenshot from 2015-08-10 17 59 39](https://cloud.githubusercontent.com/assets/5924185/9176557/51a85db4-3f8c-11e5-8954-58bd99804eb3.png)
![screenshot from 2015-08-10 18 01 04](https://cloud.githubusercontent.com/assets/5924185/9176556/51a5d4a4-3f8c-11e5-8895-ccb13dff5ba1.png)
![screenshot from 2015-08-10 18 01 21](https://cloud.githubusercontent.com/assets/5924185/9176558/51a8982e-3f8c-11e5-9daf-97035fb45c61.png)

**Comment by drvic10k** [comment]
fixed by 11d992d4278301b15b08db2e226b3f1c94137644
